# -*- coding: utf-8 -*-
"""train_pint.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P6hKS-cc4siMDaJ12CXMw-FCaDSpku0B
"""

# =============================================================================================
# 0) Install + Imports
# =============================================================================================
!pip -q install pythainlp scikit-learn

import json
import numpy as np
import pandas as pd

from pythainlp.tokenize import word_tokenize
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import layers

print("TF:", tf.__version__)


# =============================================================================================
# 1) Upload cleaned JSON
# =============================================================================================
# from google.colab import files
# uploaded = files.upload()

# json_path = list(uploaded.keys())[0]
# print("Loaded:", json_path)

from google.colab import drive
drive.mount('/content/drive')
# json_path = "/content/drive/MyDrive/cleaned_train_sentiment.json"
json_path = "/content/drive/MyDrive/train_sentiment.cleaned.json"

with open(json_path, "r", encoding="utf-8") as f:
    data = json.load(f)

texts = data["text"]
sentiments = data["sentiment"]

rows = []
for k, t in texts.items():
    if k in sentiments:
        rows.append((k, t, sentiments[k]))

df = pd.DataFrame(rows, columns=["id", "text", "sentiment"])
print(df.shape)
df.head()

# ====================================================================================================
# 2) Tokenize Thai (word-level)
# ====================================================================================================
def tokenize_th(s: str):
    # ใช้ newmm เสถียร + เก็บ token พวก <DATE> <POS_EMO> ได้เป็นคำ
    toks = word_tokenize(str(s), engine="newmm", keep_whitespace=False)
    return toks

df["tokens"] = df["text"].map(tokenize_th)
df["text_tok"] = df["tokens"].map(lambda toks: " ".join(toks))
df[["text", "text_tok", "sentiment"]].head(3)


# ======================================================================================================
# 3) Encode labels
# ======================================================================================================
label2id = {"negative": 0, "neutral": 1, "positive": 2}
df["y"] = df["sentiment"].map(label2id)

# ตรวจว่ามี label หลุดไหม
if df["y"].isna().any():
    bad = df[df["y"].isna()]["sentiment"].value_counts()
    raise ValueError(f"Found unknown labels:\n{bad}")

print(df["y"].value_counts())


# ===============================================================================================================
# 4) Split 70/15/15 (stratified)
# ===============================================================================================================
X = df["text_tok"].values
y = df["y"].values

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

print("train:", len(X_train), "val:", len(X_val), "test:", len(X_test))



# ===============================================================================================================
# 4) Split 70/15/15 (stratified)
# ===============================================================================================================
X = df["text_tok"].values
y = df["y"].values

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

print("train:", len(X_train), "val:", len(X_val), "test:", len(X_test))

# ============================================================
# 🔥 STACKING (SVM + LR + NB + GRADIENT BOOST)
# ============================================================

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.calibration import CalibratedClassifierCV
from sklearn.decomposition import TruncatedSVD
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.preprocessing import StandardScaler

# ============================================================
# 1️⃣ TF-IDF
# ============================================================

vectorizer = TfidfVectorizer(
    max_features=80000,
    ngram_range=(1,3),
    min_df=2,
    sublinear_tf=True
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec  = vectorizer.transform(X_test)

n_classes = len(np.unique(y_train))

# ============================================================
# 2️⃣ SVD for Gradient Boosting
# ============================================================

svd = TruncatedSVD(n_components=300, random_state=42)
X_train_svd = svd.fit_transform(X_train_vec)
X_test_svd  = svd.transform(X_test_vec)

scaler_svd = StandardScaler()
X_train_svd = scaler_svd.fit_transform(X_train_svd)
X_test_svd  = scaler_svd.transform(X_test_svd)

# เพิ่มอันนี้
X_val_vec = vectorizer.transform(X_val)

# สำหรับ SVD
X_val_svd = svd.transform(X_val_vec)
X_val_svd = scaler_svd.transform(X_val_svd)

# ============================================================
# 3️⃣ Base Models
# ============================================================

svm = CalibratedClassifierCV(
    LinearSVC(C=1.5),
    method="sigmoid",
    cv=3
)

lr = LogisticRegression(max_iter=3000)
nb = MultinomialNB(alpha=0.5)

gb = HistGradientBoostingClassifier(
    max_depth=6,
    learning_rate=0.1,
    max_iter=200
)

base_models_sparse = [svm, lr, nb]
base_models_dense  = [gb]

# ============================================================
# 4️⃣ OOF Stacking
# ============================================================

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

total_models = len(base_models_sparse) + len(base_models_dense)
oof_train = np.zeros((X_train_vec.shape[0], n_classes * total_models))
oof_test  = np.zeros((X_test_vec.shape[0], n_classes * total_models))

model_index = 0

# ---- Sparse models (SVM, LR, NB)
for model in base_models_sparse:

    oof_test_fold = np.zeros((X_test_vec.shape[0], n_classes, 5))

    for fold, (train_idx, val_idx) in enumerate(skf.split(X_train_vec, y_train)):

        X_tr, X_val_fold = X_train_vec[train_idx], X_train_vec[val_idx]
        y_tr = y_train[train_idx]

        model.fit(X_tr, y_tr)

        val_proba = model.predict_proba(X_val_fold)
        test_proba = model.predict_proba(X_test_vec)

        oof_train[val_idx, model_index*n_classes:(model_index+1)*n_classes] = val_proba
        oof_test_fold[:, :, fold] = test_proba

    oof_test[:, model_index*n_classes:(model_index+1)*n_classes] = oof_test_fold.mean(axis=2)
    model_index += 1


# ---- Dense model (Gradient Boosting)
for model in base_models_dense:

    oof_test_fold = np.zeros((X_test_svd.shape[0], n_classes, 5))

    for fold, (train_idx, val_idx) in enumerate(skf.split(X_train_svd, y_train)):

        X_tr, X_val_fold = X_train_svd[train_idx], X_train_svd[val_idx]
        y_tr = y_train[train_idx]

        model.fit(X_tr, y_tr)

        val_proba = model.predict_proba(X_val_fold)
        test_proba = model.predict_proba(X_test_svd)

        oof_train[val_idx, model_index*n_classes:(model_index+1)*n_classes] = val_proba
        oof_test_fold[:, :, fold] = test_proba

    oof_test[:, model_index*n_classes:(model_index+1)*n_classes] = oof_test_fold.mean(axis=2)
    model_index += 1


# ============================================================
# 5️⃣ Meta Learner
# ============================================================

meta_model = LogisticRegression(max_iter=3000)
meta_model.fit(oof_train, y_train)

train_pred = meta_model.predict(oof_train)
test_pred  = meta_model.predict(oof_test)

print("\n🔥 STACKING RESULTS (WITH GRADIENT BOOST)")
print("Train Acc:", accuracy_score(y_train, train_pred))
print("Test Acc :", accuracy_score(y_test, test_pred))
print(classification_report(y_test, test_pred, digits=4))
print(confusion_matrix(y_test, test_pred))

# ============================================================
# 🔎 BASE MODEL TRAIN ACC (Correct Version)
# ============================================================

# print("\n--- Base Model Train Accuracy (Full Train Fit) ---")

# # ----- Sparse Models
# for model in base_models_sparse:
#     model.fit(X_train_vec, y_train)
#     train_acc = accuracy_score(y_train, model.predict(X_train_vec))
#     test_acc  = accuracy_score(y_test, model.predict(X_test_vec))
#     print(f"{model.__class__.__name__}: Train={train_acc:.4f} | Test={test_acc:.4f}")

# # ----- Dense Model (Gradient Boost)
# for model in base_models_dense:
#     model.fit(X_train_svd, y_train)
#     train_acc = accuracy_score(y_train, model.predict(X_train_svd))
#     test_acc  = accuracy_score(y_test, model.predict(X_test_svd))
#     print(f"{model.__class__.__name__}: Train={train_acc:.4f} | Test={test_acc:.4f}")

print("\n--- Base Model Accuracy (Full Train Fit) ---")

# ----- Sparse Models
for model in base_models_sparse:
    model.fit(X_train_vec, y_train)

    train_acc = accuracy_score(y_train, model.predict(X_train_vec))
    val_acc   = accuracy_score(y_val, model.predict(X_val_vec))
    test_acc  = accuracy_score(y_test, model.predict(X_test_vec))

    print(f"{model.__class__.__name__}: "
          f"Train={train_acc:.4f} | "
          f"Val={val_acc:.4f} | "
          f"Test={test_acc:.4f}")

# ----- Dense Model (Gradient Boost)
for model in base_models_dense:
    model.fit(X_train_svd, y_train)

    train_acc = accuracy_score(y_train, model.predict(X_train_svd))
    val_acc   = accuracy_score(y_val, model.predict(X_val_svd))
    test_acc  = accuracy_score(y_test, model.predict(X_test_svd))

    print(f"{model.__class__.__name__}: "
          f"Train={train_acc:.4f} | "
          f"Val={val_acc:.4f} | "
          f"Test={test_acc:.4f}")

    # สร้าง meta feature ของ val set

meta_val = np.zeros((X_val_vec.shape[0], n_classes * total_models))
model_index = 0

# sparse models
for model in base_models_sparse:
    model.fit(X_train_vec, y_train)
    val_proba = model.predict_proba(X_val_vec)

    meta_val[:, model_index*n_classes:(model_index+1)*n_classes] = val_proba
    model_index += 1

# dense model
for model in base_models_dense:
    model.fit(X_train_svd, y_train)
    val_proba = model.predict_proba(X_val_svd)

    meta_val[:, model_index*n_classes:(model_index+1)*n_classes] = val_proba
    model_index += 1

# predict
val_pred = meta_model.predict(meta_val)

print("\n🔥 STACKING VAL ACC:", accuracy_score(y_val, val_pred))

# retrain base models on full train
for model in base_models_sparse:
    model.fit(X_train_vec, y_train)

for model in base_models_dense:
    model.fit(X_train_svd, y_train)

import joblib

joblib.dump({
    "vectorizer": vectorizer,
    "svd": svd,
    "scaler_svd": scaler_svd,
    "base_models_sparse": base_models_sparse,
    "base_models_dense": base_models_dense,
    "meta_model": meta_model,
    "n_classes": n_classes
}, "sentiment_stacking.pkl")

print("Saved successfully")

from google.colab import files
files.download("sentiment_stacking.pkl")

# # ===== เพิ่ม bigram ===========================================================================================
# def add_bigrams_to_text(text):
#     tokens = text.split()
#     bigrams = []
#     for i in range(len(tokens) - 1):
#         bigrams.append(tokens[i] + "_" + tokens[i+1])
#     tokens = tokens + bigrams
#     return " ".join(tokens)

# # apply กับ train/val/test
# X_train = [add_bigrams_to_text(t) for t in X_train]
# X_val   = [add_bigrams_to_text(t) for t in X_val]
# X_test  = [add_bigrams_to_text(t) for t in X_test]

# # ===============================================================================================================
# # 5) Vectorize (Tokenizer + padding)
# # ===============================================================================================================
# VOCAB_SIZE = 40000   # เพิ่ม vocab นิด เพราะมี bigram
# MAX_LEN = 200

# tokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token="<OOV>")
# tokenizer.fit_on_texts(X_train)

# def to_padded(texts):
#     seq = tokenizer.texts_to_sequences(texts)
#     return pad_sequences(seq, maxlen=MAX_LEN, padding="post", truncating="post")

# X_train_pad = to_padded(X_train)
# X_val_pad   = to_padded(X_val)
# X_test_pad  = to_padded(X_test)

# print(X_train_pad.shape, X_val_pad.shape, X_test_pad.shape)


# # ===============================================================================================================
# # 6) Build TextCNN + Trainable Embedding
# # ===============================================================================================================
# EMBED_DIM = 128
# NUM_CLASSES = 3

# def build_textcnn(vocab_size, embed_dim, max_len, num_classes):
#     inp = layers.Input(shape=(max_len,), dtype="int32")

#     x = layers.Embedding(
#         input_dim=vocab_size,
#         output_dim=embed_dim,
#         input_length=max_len,
#         mask_zero=False
#     )(inp)

#     convs = []
#     for k in [2,3,4,5]:
#         c = layers.Conv1D(filters=64, kernel_size=k, activation="relu", padding="valid")(x)
#         c = layers.BatchNormalization()(c)
#         c = layers.GlobalMaxPooling1D()(c)
#         convs.append(c)

#     x = layers.Concatenate()(convs)
#     x = layers.Dropout(0.5)(x)
#     x = layers.Dense(128, activation="relu")(x)
#     x = layers.Dropout(0.3)(x)
#     out = layers.Dense(num_classes, activation="softmax")(x)

#     model = tf.keras.Model(inp, out)
#     model.compile(
#         optimizer=tf.keras.optimizers.Adam(1e-4),
#         loss="sparse_categorical_crossentropy",
#         metrics=["accuracy"]
#     )
#     return model

# model = build_textcnn(VOCAB_SIZE, EMBED_DIM, MAX_LEN, NUM_CLASSES)
# model.summary()

# import random
# import numpy as np
# import tensorflow as tf

# SEED = 42

# random.seed(SEED)
# np.random.seed(SEED)
# tf.random.set_seed(SEED)

# from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

# checkpoint = ModelCheckpoint(
#     "best.keras",              # ชื่อไฟล์
#     monitor="val_accuracy",    # ดูจาก validation
#     mode="max",
#     save_best_only=True,
#     verbose=1
# )

# early = EarlyStopping(
#     monitor="val_accuracy",
#     mode="max",
#     patience=2,
#     restore_best_weights=True
# )

# reduce_lr = ReduceLROnPlateau(
#     monitor="val_loss",
#     factor=0.5,
#     patience=1
# )

# history = model.fit(
#     X_train_pad, y_train,
#     validation_data=(X_val_pad, y_val),
#     epochs=20,
#     batch_size=32,
#     callbacks=[checkpoint, early, reduce_lr]
# )



#************************************************************************************************************


# # ============================================================
# # 🔥 ULTIMATE ENSEMBLE (Deep + SVM) - ONE CELL
# # ============================================================

# import numpy as np
# import tensorflow as tf
# from tensorflow.keras import layers
# from tensorflow.keras import backend as K
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.svm import LinearSVC
# from sklearn.utils.class_weight import compute_class_weight
# from sklearn.metrics import classification_report, confusion_matrix

# # ============================================================
# # 1️⃣ TF-IDF + SVM (Strong Classical Baseline)
# # ============================================================

# vectorizer = TfidfVectorizer(
#     max_features=50000,
#     ngram_range=(1,2)
# )

# X_train_vec = vectorizer.fit_transform(X_train)
# X_val_vec   = vectorizer.transform(X_val)
# X_test_vec  = vectorizer.transform(X_test)

# svm = LinearSVC()
# svm.fit(X_train_vec, y_train)

# print("SVM Val Acc:", svm.score(X_val_vec, y_val))


# # ============================================================
# # 2️⃣ Deep Model Preparation
# # ============================================================

# VOCAB_SIZE = 40000
# MAX_LEN = 200
# NUM_CLASSES = 3

# tokenizer = tf.keras.preprocessing.text.Tokenizer(
#     num_words=VOCAB_SIZE,
#     oov_token="<OOV>"
# )
# tokenizer.fit_on_texts(X_train)

# def to_pad(texts):
#     seq = tokenizer.texts_to_sequences(texts)
#     return tf.keras.preprocessing.sequence.pad_sequences(
#         seq, maxlen=MAX_LEN, padding="post", truncating="post"
#     )

# X_train_pad = to_pad(X_train)
# X_val_pad   = to_pad(X_val)
# X_test_pad  = to_pad(X_test)


# # ============================================================
# # 3️⃣ Class Weights
# # ============================================================

# class_weights = compute_class_weight(
#     class_weight="balanced",
#     classes=np.unique(y_train),
#     y=y_train
# )
# class_weights = dict(enumerate(class_weights))


# # ============================================================
# # 4️⃣ Attention Layer
# # ============================================================

# class Attention(layers.Layer):
#     def build(self, input_shape):
#         self.W = self.add_weight(
#             shape=(input_shape[-1], 1),
#             initializer="glorot_uniform"
#         )
#         self.b = self.add_weight(
#             shape=(input_shape[1], 1),
#             initializer="zeros"
#         )
#         super().build(input_shape)

#     def call(self, x):
#         e = K.tanh(K.dot(x, self.W) + self.b)
#         a = K.softmax(e, axis=1)
#         return K.sum(x * a, axis=1)


# # ============================================================
# # 5️⃣ Hybrid Deep Model
# # ============================================================

# from tensorflow.keras import regularizers

# def build_model():
#     inp = layers.Input(shape=(MAX_LEN,))

#     x = layers.Embedding(VOCAB_SIZE, 128)(inp)
#     x = layers.SpatialDropout1D(0.4)(x)

#     x = layers.Conv1D(
#         96,
#         3,
#         padding="same",
#         activation="relu",
#         kernel_regularizer=regularizers.l2(1e-4)
#     )(x)

#     x = layers.BatchNormalization()(x)

#     x = layers.Bidirectional(
#         layers.LSTM(
#             64,
#             return_sequences=True,
#             dropout=0.4
#         )
#     )(x)

#     x = Attention()(x)

#     x = layers.Dense(
#         128,
#         activation="relu",
#         kernel_regularizer=regularizers.l2(1e-4)
#     )(x)

#     x = layers.Dropout(0.5)(x)

#     out = layers.Dense(NUM_CLASSES, activation="softmax")(x)

#     model = tf.keras.Model(inp, out)

#     model.compile(
#         optimizer=tf.keras.optimizers.Adam(5e-4),
#         loss="sparse_categorical_crossentropy",
#         metrics=["accuracy"]
#     )

#     return model


# model = build_model()
# model.summary()


# # ============================================================
# # 6️⃣ Callbacks
# # ============================================================

# callbacks = [
#     tf.keras.callbacks.EarlyStopping(
#         monitor="val_accuracy",
#         patience=3,
#         restore_best_weights=True
#     ),
#     tf.keras.callbacks.ReduceLROnPlateau(
#         monitor="val_loss",
#         factor=0.5,
#         patience=1
#     )
# ]


# # ============================================================
# # 7️⃣ Train Deep Model
# # ============================================================

# history = model.fit(
#     X_train_pad, y_train,
#     validation_data=(X_val_pad, y_val),
#     epochs=25,
#     batch_size=64,
#     class_weight=class_weights,
#     callbacks=callbacks,
#     verbose=1
# )


# # ============================================================
# # 8️⃣ Ensemble (Deep + SVM)
# # ============================================================

# # Deep probabilities
# deep_probs = model.predict(X_test_pad)

# # SVM pseudo-prob (distance -> softmax)
# svm_decision = svm.decision_function(X_test_vec)
# svm_probs = tf.nn.softmax(svm_decision).numpy()

# # Ensemble average
# final_probs = (deep_probs + svm_probs) / 2
# y_pred = np.argmax(final_probs, axis=1)

# print("\n🔥 FINAL ENSEMBLE RESULTS")
# print(classification_report(y_test, y_pred, digits=4))
# print(confusion_matrix(y_test, y_pred))

# ===============================================================================================================
# 8) Evaluate on TEST
# ===============================================================================================================
test_loss, test_acc = model.evaluate(X_test_pad, y_test, verbose=0)
print("TEST acc:", test_acc)

y_pred = model.predict(X_test_pad, verbose=0).argmax(axis=1)

print("\nClassification report:")
print(classification_report(y_test, y_pred, target_names=["negative","neutral","positive"]))

print("\nConfusion matrix:")
print(confusion_matrix(y_test, y_pred))

print("\n🔥 Validated RESULTS")
print(classification_report(y_val, val_pred, digits=4))
print(confusion_matrix(y_val, val_pred))

from tensorflow.keras import mixed_precision
mixed_precision.set_global_policy("mixed_float16")

# ===== SAVE MODEL =====
model.save("best.keras")

# ===== SAVE TOKENIZER =====
import pickle
with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

print("Saved model + tokenizer")

from google.colab import files
files.download("best.keras")
files.download("tokenizer.pkl")